from pathlib import Path
import json
ROOT=Path(__file__).parent/'dist'
events=[
 dict(name='Haldi',slug='haldi',time='Friday · 10:00 AM',bg='#f0c849',ink='#493514',img='haldi',line='A little sunshine. A lot of joy.',desc='Marigolds, mischief, and everyone you love. The weekend begins in a courtyard full of colour.',detail='In the plan: shaded seating, a fresh-towel station, and a change of clothes before lunch.'),
 dict(name='Mehendi',slug='mehendi',time='Friday · 4:00 PM',bg='#234536',ink='#f1e2b4',img='mehendi',line='Let the afternoon linger.',desc='Henna-dark hands, familiar songs, and stories shared over chai. There is room for the unhurried moments.',detail='In the plan: artist rotations, easy-to-eat plates, and enough time for every intricate detail.'),
 dict(name='Sangeet',slug='sangeet',time='Friday · 8:00 PM',bg='#2f2143',ink='#e7c8ef',img='sangeet',line='The night belongs to everyone.',desc='From the first family performance to the last song nobody wants to end. A celebration with a rhythm of its own.',detail='In the plan: rehearsals, sound checks, performance cues, and a late-night supper.'),
 dict(name='Pheras',slug='pheras',time='Saturday · 5:30 PM',bg='#8a263b',ink='#ffe8c6',img='ceremony',line='Everything leads to this.',desc='The light softens. The music slows. Seven promises, two families, and a moment held with care.',detail='In the plan: the auspicious hour, guest arrivals, ceremony essentials, and a discreet weather backup.'),
 dict(name='Reception',slug='reception',time='Saturday · 8:00 PM',bg='#1e2c3b',ink='#efd6a2',img='reception',line='One more toast. One more dance.',desc='Dinner beneath warm lights, speeches from the heart, and a dance floor that feels like home.',detail='In the plan: the seating chart, dietary notes, speech timings, and a seamless change of scene.'),
 dict(name='Farewell',slug='farewell',time='Sunday · 10:00 AM',bg='#e5c8b2',ink='#4b352b',img='destination',line='Until we meet again.',desc='A slow breakfast. The last embraces. Everyone carries a little of the weekend home.',detail='In the plan: luggage collection, breakfast boxes, and departures coordinated to the final flight.')]
stories=[
dict(slug='tara-and-arjun',couple='Tara & Arjun',venue='Taj Lake Palace',city='Udaipur',year='2025',guests='240',events='6',img='ceremony',paper='#f5eadc',ink='#753644',mood='#d9b890',font="'Italiana',Georgia,serif",palette=['#753644','#d9b890','#f7e8d2','#b77d54'],title='A palace, a lake, and a weekend of belonging.',desc='A lakeside celebration imagined around rose, ivory, and the quiet glow of candlelight. Six gatherings, each with its own mood, held together by one thoughtful plan.',solved='A change in the weather, without a change in the feeling. An indoor ceremony layout was ready before the first raindrop.',problem='Weather & guest movement',notes='The ceremony had two complete layouts. A held indoor space, duplicated floral inventory, and clear transport cues meant the decision could be made without involving the couple.',run=[['15:30','Weather decision','Production lead confirms the courtyard or indoor ceremony layout.'],['16:00','Guest transfers','Hosts greet guests at the arrival point and guide them to refreshments.'],['17:00','Baraat arrival','The music lead, family coordinator, and hospitality team move on one cue.'],['17:30','Pheras','Ceremony begins; the dinner team quietly readies the next space.'],['19:15','A moment for two','Portrait time is protected while guests enjoy aperitifs.']]),
dict(slug='ira-and-kabir',couple='Ira & Kabir',venue='Sofitel Zallaq',city='Bahrain',year='2025',guests='400',events='5',img='reception',paper='#eaf0ee',ink='#1b4e50',mood='#a9c3b8',font='Georgia,serif',palette=['#1b4e50','#a9c3b8','#efd8b4','#eaf0ee'],title='Two cities. Many journeys. One shared shore.',desc='An imagined destination weekend that brings two families together by the Arabian Gulf. Sea-glass green, warm brass, and generous evenings at the table.',solved='400 guests arriving on different flights. One arrival desk, grouped transfers, and a single point of contact for every family.',problem='International arrivals',notes='Flight details are grouped by arrival window. Hospitality hosts manage room readiness, transfers, and welcome packs while the production team stays focused on the celebrations.',run=[['12:00','Arrival desk opens','The hospitality lead checks flight updates and room release times.'],['14:00','Welcome lunch','Early arrivals have a place to settle in before check-in.'],['16:00','Family rehearsal','A compact cue-to-cue rehearsal checks music and entrances.'],['18:30','Doors open','Guest hosts share table assignments and dietary notes with service.'],['20:00','Dinner & toasts','Speeches are timed between courses, with space for the unexpected.']]),
dict(slug='mira-and-dev',couple='Mira & Dev',venue='Alila Diwa',city='Goa',year='2024',guests='120',events='4',img='sangeet',paper='#f2eee4',ink='#3f4c30',mood='#c5c7a6',font="'Italiana',Georgia,serif",palette=['#3f4c30','#c5c7a6','#cc8d6b','#f2eee4'],title='A garden party that became a wedding.',desc='An intimate concept of slow afternoons, garden greens, and candlelit dinners. The kind of weekend where every guest feels part of the family.',solved='A late venue change, with the guest experience intact. The layout, supplier access, and transport plan were rebuilt around the new setting.',problem='A new venue, a familiar feeling',notes='A revised floor plan is shared with every supplier. One walkthrough resolves power, access, and guest paths before the build begins; the couple receives one clear update.',run=[['09:00','Supplier access','Vehicles arrive in assigned windows, with a clear unloading route.'],['11:00','Layout sign-off','The planner checks aisle widths, shade, power, and service paths.'],['15:00','Guest welcome','The hosting team opens the garden with drinks and soft music.'],['17:00','Ceremony','A small gathering, with every seat close to the moment.'],['19:00','Dinner in the garden','Candles are lit and guests settle into a long, relaxed meal.']])]
def image(name,alt,cls='',eager=False):
 return f'<img class="{cls}" src="/assets/{name}.webp" alt="{alt}" loading="{"eager" if eager else "lazy"}" decoding="async" width="1600" height="1067">'
def loading_intro():
 return '<div class="site-loader" aria-label="Opening Saanjh"><div class="loader-panel"></div><div class="loader-panel"></div><div class="loader-identity"><div class="loader-name" aria-label="Saanjh">'+''.join(f'<span aria-hidden="true" style="--letter:{i}">{c}</span>' for i,c in enumerate('saanjh'))+'</div><p>From first thought to final farewell</p><span class="loader-rule" aria-hidden="true"></span></div><button class="loader-skip" type="button">Skip intro</button></div>'
def head(title,desc,theme='',include_map=False):
 return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="{desc}"><meta name="theme-color" content="#481c2a"><title>{title}</title><script>try {{if ((location.pathname==='/' || location.pathname==='/index.html') && !location.hash && !matchMedia('(prefers-reduced-motion: reduce)').matches && !sessionStorage.getItem('saanjh-intro-seen-v2')) {{document.documentElement.classList.add('loading-intro');window.__saanjhIntroStarted=performance.now();window.__saanjhIntroFallback=setTimeout(function(){{document.documentElement.classList.remove('loading-intro','intro-leaving');}},8000);}}}} catch (e) {{}}</script><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/motion.css">{('<link rel="stylesheet" href="/assets/leaflet.css">' if include_map else '')}</head><body {theme}><a class="skip" href="#main">Skip to content</a>'''
def nav():
 return '''<header class="nav"><a class="brand" href="/" aria-label="Saanjh home">saanjh<span>Wedding atelier</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation">Menu</button><nav class="navlinks" id="navigation" aria-label="Main navigation"><a href="/#weekend">The weekend</a><a href="/#stories">Our stories</a><a href="/#destinations">Destinations</a><a class="enquire" href="/#brief">Begin your story</a></nav></header>'''
def footer(include_map=False):
 map_scripts='<script src="/assets/leaflet.js"></script><script src="/assets/world-map.js"></script>' if include_map else ''
 return '''<footer class="footer"><div class="footer-top"><a class="brand" href="/">saanjh</a><p>From the first thought<br>to the final farewell.</p></div><div class="footer-bottom"><span>© 2026 Saanjh · A wedding planner concept by Copywrk</span><span>Sample stories & figures · Illustrative stock photography</span><a href="/credits/">Image credits</a></div></footer>''' + map_scripts + '<script src="/app.js"></script></body></html>'
home=head('Saanjh — From first thought to final farewell','A destination wedding planner concept. Explore a whole wedding weekend, go behind the plan, and build your wedding brief.',include_map=True)+loading_intro()+nav()
home+='''<main id="main" tabindex="-1"><section class="hero" aria-label="Saanjh wedding atelier">'''+image('ceremony','A wedding ceremony beneath a pink and ivory floral mandap',eager=True)+'''<div class="hero-top eyebrow">For the moments that become everything</div><div class="hero-content"><h1>A weekend.<br><em>A lifetime.</em></h1><div class="hero-copy"><p>Many celebrations. One beautifully considered whole. Weddings imagined around you, from the first thought to the final farewell.</p><a class="textlink" href="#weekend">Step into the weekend</a></div></div><div class="hero-bottom"><span>India & destinations beyond</span><span>Scroll to celebrate</span></div></section><section class="intro wrap"><span class="eyebrow">The art of bringing it all together</span><div class="reveal"><h2>You live every moment.<br>We hold every detail.</h2><p>A wedding is more than the day. It is the welcome, the laughter between events, the right song at the right time. We give the whole weekend a feeling — and a plan.</p></div></section><section class="weekend" id="weekend" aria-label="A wedding weekend in six chapters"><div class="weekend-heading"><span class="eyebrow">From first thought to final farewell</span><span class="eyebrow">One weekend · Six chapters</span></div><div class="weekend-grid"><div class="weekend-picture" aria-hidden="true"><div class="photo-stage">'''
for i,e in enumerate(events):home+=image(e['img'],e['name']+' wedding inspiration','active' if i==0 else '',i==0)
home+='''</div><div class="photo-caption"><span id="photo-day">Friday · 10:00 AM</span><span id="photo-count">01 / 06</span></div></div><div class="event-sequence">'''
for i,e in enumerate(events):
 home+=f'''<article class="event" id="{e['slug']}" data-index="{i}" data-bg="{e['bg']}" data-ink="{e['ink']}"><span class="num">0{i+1}</span><h3>{e['name']}</h3><div class="moment">{e['time']}</div><p>{e['line']}<br><br>{e['desc']}</p>{image(e['img'],e['name']+' illustrative wedding photograph','mobile-event-img')}<div class="detail">{e['detail']}</div></article>'''
home+='</div></div><nav class="weekend-progress" aria-label="Wedding chapters">'+''.join(f'<a href="#{e["slug"]}" class="{"active" if i==0 else ""}">{e["name"]}</a>' for i,e in enumerate(events))+'</nav></section>'
home+='''<section class="stories wrap" id="stories"><div class="section-title"><div><div class="eyebrow">The story ledger</div><h2>Love, in the details.</h2></div><p>Go behind the celebration.<br>See the thinking that holds it together.</p></div><div class="ledger-head" aria-hidden="true"><span>Couple</span><span>Setting</span><span>City</span><span>Year</span><span>Guests</span><span>Events</span></div>'''
for s in stories:
 home+=f'''<a class="ledger-row" href="/stories/{s['slug']}/" data-photo="{s['img']}" aria-label="Read the sample planning story for {s['couple']}">{image(s['img'], 'Wedding inspiration for this sample story','mobile-story-photo')}<span class="couple">{s['couple']}</span><span data-label="Setting">{s['venue']}</span><span data-label="City">{s['city']}</span><span data-label="Year">{s['year']}</span><span class="count" data-label="Guests">{s['guests']}</span><span class="count" data-label="Events">0{s['events']}</span></a>'''
home+='''<p class="sample-note">Three illustrative planning stories. Names, event counts and guest figures are fictional; photography is for inspiration.</p></section><div class="hover-photo" aria-hidden="true"><img alt="" src="/assets/ceremony.webp"></div><section class="venues" id="destinations"><div class="wrap"><div class="section-title"><div><div class="eyebrow">A sense of place</div><h2>Where it all begins.</h2></div><p>A lakeside palace. A garden in Goa. A gathering by the Gulf.</p></div><div class="atlas"><div class="map-shell"><div class="map-fallback">India<br>& the Arabian Gulf</div><div id="venue-map" role="region" aria-label="Map of suggested destination cities"></div><span class="map-label">A destination shortlist</span></div><div class="venue-list"><button class="venue-select" data-venue="0" aria-pressed="true"><span class="eyebrow">01 · Udaipur, India</span><strong>Taj Lake Palace</strong><small>A lake setting for a celebration with a sense of arrival.</small></button><button class="venue-select" data-venue="1" aria-pressed="false"><span class="eyebrow">02 · Zallaq, Bahrain</span><strong>Sofitel Bahrain</strong><small>A Gulf-side setting for bringing far-flung families together.</small></button><button class="venue-select" data-venue="2" aria-pressed="false"><span class="eyebrow">03 · Majorda, Goa</span><strong>Alila Diwa</strong><small>A garden setting for a slower, more intimate weekend.</small></button><button class="venue-select" data-venue="3" aria-pressed="false"><span class="eyebrow">04 · Jaipur, India</span><strong>Fairmont Jaipur</strong><small>A palace-inspired backdrop for a celebration with scale.</small></button><div class="venue-links"><a id="venue-official" class="textlink" href="https://www.tajhotels.com/en-in/hotels/taj-lake-palace-udaipur" target="_blank" rel="noopener">Explore the venue</a><a id="venue-directions" class="textlink" href="https://www.google.com/maps/search/?api=1&query=Taj+Lake+Palace+Udaipur" target="_blank" rel="noopener">View on Maps</a></div></div></div><p class="sample-note">Suggested venues, not claimed partnerships. Map pins indicate destination cities; availability is confirmed with each venue.</p></div></section><section class="brief-section wrap" id="brief"><div class="brief-layout"><div class="brief-intro"><div class="eyebrow">Your celebration, your way</div><h2>It begins<br>with a thought.</h2><p>Tell us the shape of your weekend. A place, a season, the people you love — we can take it from there.</p><p class="small">Not sure of a detail yet? Choose “Still deciding.” Your brief is a starting point, not a commitment.</p></div><form class="brief-form" id="brief-form">'''
groups=[('city','Where do you imagine it?',['Udaipur','Bahrain','Goa','Jaipur','Other','Still deciding']),('season','Which season feels right?',['Winter','Spring','Summer','Autumn','Still deciding']),('guests','How many people are joining?',['Under 100','100–200','200–400','400+','Still deciding']),('events','Which moments shall we plan?',[e['name'] for e in events])]
for i,(name,label,values) in enumerate(groups):
 home+=f'<fieldset><legend><span>0{i+1}</span>{label}</legend><div class="chips">'
 for j,value in enumerate(values):
  checked=' checked' if (name=='events' and value in ['Haldi','Pheras','Reception']) or (name!='events' and value=='Still deciding') else ''
  home+=f'<label class="chip"><input type="{"checkbox" if name=="events" else "radio"}" name="{name}" value="{value}"{checked}><span>{value}</span></label>'
 home+='</div>'
 if name=='city':home+='<input id="other-city" class="other-city" placeholder="Your city or destination" aria-label="Other city or destination" maxlength="100" hidden>'
 home+='</fieldset>'
home+='''<div class="brief-preview"><label class="eyebrow" for="brief-message">Your wedding brief</label><textarea id="brief-message" aria-label="Editable WhatsApp wedding brief">Hello! I'd like to discuss planning our wedding weekend.

Destination: Still deciding
Season: Still deciding
Guest count: Still deciding
Events: Haldi, Pheras, Reception

Could we talk about the possibilities and next steps?</textarea><noscript><p class="sample-note">Automatic updates need JavaScript. You can edit this brief and copy it into WhatsApp.</p></noscript><div class="brief-actions"><button class="button" type="button" id="whatsapp-brief">Open in WhatsApp</button><button class="button secondary" type="button" id="copy-brief">Copy brief</button></div><p class="brief-status" id="brief-status" role="status" aria-live="polite"></p><p class="sample-note">Demo: no planner number is connected. WhatsApp opens with your brief so you can choose a recipient. Nothing is sent automatically.</p></div></form></div></section></main>'''+footer(True)
ROOT.joinpath('index.html').write_text(home)
for s in stories:
 theme=f'''style="--paper:{s['paper']};--ink:{s['ink']};--line:{s['ink']}30;--mood:{s['mood']};--serif:{s['font']}"'''
 page=head(s['couple']+' — Behind the plan | Saanjh',s['title']+' An illustrative wedding planning case study.',theme)+nav()+f'''<main id="main" tabindex="-1"><section class="story-hero wrap"><a class="back" href="/#stories">Back to the story ledger</a><div class="story-heading"><div><div class="eyebrow">{s['city']} · {s['year']} · Illustrative story</div><h1>{s['couple']}</h1></div><p>{s['title']}</p></div>{image(s['img'],'Illustrative wedding photography, not an actual Saanjh client','story-cover',True)}<div class="story-meta">'''
 for label,key in [('Setting','venue'),('City','city'),('Year','year'),('Guests','guests'),('Events','events')]:page+=f'<div><span>{label}</span><strong>{s[key]}</strong></div>'
 page+=f'''</div><p class="sample-note">Fictional couple and planning scenario. All photographs are illustrative stock images and do not depict this claimed wedding.</p></section><section class="story-design wrap"><div><span class="eyebrow">From an idea to a feeling</span><h2>The thought.<br>The moment.</h2><p>{s['desc']}</p><div class="palette" aria-label="Wedding palette">'''+''.join(f'<span class="swatch" style="background:{c}" title="{c}"></span>' for c in s['palette'])+'''</div><span class="eyebrow">The wedding palette</span></div><div><div class="comparison">'''+image(s['img'],'Final photograph inspiration')+f'''<div class="mood-board">{image('mehendi' if s['city']=='Goa' else 'haldi-bride','Moodboard texture and colour inspiration')}<div class="mood-details"><span class="eyebrow">The mood</span><strong>{'Rose &<br>candlelight' if s['city']=='Udaipur' else 'Sea glass &<br>warm brass' if s['city']=='Bahrain' else 'Garden &<br>golden hour'}</strong><div class="mood-swatch"></div><span class="eyebrow">{s['city']} / {s['year']}</span></div></div><div class="comparison-divider"></div><div class="compare-labels"><span>Moodboard concept</span><span>Photo inspiration</span></div><input type="range" min="0" max="100" value="50" aria-label="Compare moodboard with final photo inspiration"></div><p class="slider-help">Drag to compare the moodboard and photo inspiration. Use arrow keys when the slider is focused.</p></div></section><section class="solved"><span class="eyebrow">What we solved · Sample scenario</span><p>{s['solved']}</p></section><section class="run-show wrap"><div class="run-layout"><div><span class="eyebrow">Behind the celebration</span><h2>{s['problem']}</h2><p>{s['notes']}</p></div><div><div class="eyebrow" style="margin-bottom:25px">An excerpt from the run of show</div>'''
 for time,title,note in s['run']:page+=f'<div class="run-row"><time>{time}</time><div><strong>{title}</strong><p>{note}</p></div></div>'
 page+='</div></div></section><section class="story-end wrap"><div class="display">What could your weekend look like?</div><a class="button" href="/#brief">Build your wedding brief</a></section></main>'+footer()
 path=ROOT/'stories'/s['slug'];path.mkdir(parents=True,exist_ok=True);(path/'index.html').write_text(page)
credits=head('Photography credits | Saanjh','Credits for illustrative wedding photography used in the Saanjh concept.')+nav()+'<main id="main" tabindex="-1" class="wrap" style="padding:80px 0"><div class="eyebrow">With thanks to the photographers</div><h1 style="font-size:72px;margin:25px 0 40px">Image credits.</h1><p>These stock photographs illustrate the concept. The pictured couples are not represented as Saanjh clients.</p>'
manifest=json.loads((Path(__file__).parent/'asset-manifest.json').read_text())
for a in manifest['assets']:credits+=f'<p style="margin-top:25px"><a class="textlink" href="{a["source_url"]}" target="_blank" rel="noopener">{a["photographer"]} · {a["license"]}</a><br>{a["description"]}</p>'
credits+='<p style="margin-top:40px">Typography: Italiana and DM Sans, included locally under the SIL Open Font License. Licence files are bundled with the fonts.</p>';credits+='<p style="margin-top:40px">Map geography: <a class="textlink" href="https://www.naturalearthdata.com/" target="_blank" rel="noopener">Natural Earth · Public domain</a>, bundled via world-atlas 2.0.2. The map is a destination overview.</p>';credits+='</main>'+footer();(ROOT/'credits').mkdir(exist_ok=True);(ROOT/'credits'/'index.html').write_text(credits)
(ROOT/'favicon.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="16" fill="#481c2a"/><text x="16" y="23" text-anchor="middle" font-family="Georgia,serif" font-size="29" fill="#f7e5ce">s</text></svg>')
(ROOT/'404.html').write_text(head('A little detour | Saanjh','Return to the wedding weekend.')+nav()+'<main id="main" tabindex="-1" class="wrap" style="padding:120px 0"><h1 style="font-size:80px">A little detour.</h1><p style="margin:30px 0">This page is not part of the weekend.</p><a class="button" href="/">Return to Saanjh</a></main>'+footer())
